### ISSUE TITLE
Decide which accelerometer axis to use for data gathering.

### ISSUE THREAD

**Issue by ttudrej** [ttudrej/showspikes#1]
https://theccontinuum.com/2012/09/24/arduino-imu-pitch-roll-from-accelerometer/

First, lmk which hardware you are using, so I can look up the specs, if needed.

Hey, seems to me like using the pitch and roll may be less useful, or at least harder to interpret than x,y,z, but I'm not sure if you have that option with your hardware.

The above link, I just looked up the hardware I think you have. Based on that, it looks like you can get 5 numbers from the accelerator, pitch, roll, sway, surge, heave, where sway/surge/heave correspond to x,y, z axis, not necessarily in that order. It seems to me that choosing one of those would simplify the the problem, that is, pick one of the axis on the board, line that axis with the vertical/plumb line, gather data, and then only pay attention to that data column, every thing else is expected to be zero.

This would be the equivalent of this simple device, up/down only:
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.seis-insight.eu%2Fen%2Fpublic-2%2Fplanetary-seismology%2Fhow-a-seismometer-works&psig=AOvVaw0hbdVLeTY0Ac1BO6C6ho-a&ust=1638195878340000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPDLgK2hu_QCFQAAAAAdAAAAABAU

The next step could be to consider all, x, y, and z, and map those out separately, or perhaps calculate the magnitude of the vector for with those components, from each data sample. Collecting all 3, combined with the knowledge of how the board is positioned and which axis correspond to which direction on the board, will allow for calculating the movement in any direction you choose, is you so desire.

**Comment by Inzi-Jack** [comment]
Roll = x axis , when x is positive +x/negative -x directionsPitch = y axis,  same as above for +y/-yAngle is Z axis in radians That’s all I need. All I am trying to do is get the magnitude, absolute value of each value down the list for Roll and pitch to maybe graph or analyze.   When I get the dataframe I won’t let me take absolute value for (seems like anyway) dtype issue but I’m not sure. It looks like I need code to go down the list, take .abs() and return the value to another type, list dataframe or tuple(?) for later manipulation.     From: Tomasz TudrejSent: Sunday, November 28, 2021 3:44 PMTo: ttudrej/showspikesCc: Inzi-Jack; AssignSubject: [ttudrej/showspikes] Decide which accelerometer axis to use for data gathering. (Issue #1) https://theccontinuum.com/2012/09/24/arduino-imu-pitch-roll-from-accelerometer/First, lmk which hardware you are using, so I can look up the specs, if needed.Hey, seems to me like using the pitch and roll may be less useful, or at least harder to interpret than x,y,z, but I'm not sure if you have that option with your hardware.The above link, I just looked up the hardware I think you have. Based on that, it looks like you can get 5 numbers from the accelerator, pitch, roll, sway, surge, heave, where sway/surge/heave correspond to x,y, z axis, not necessarily in that order. It seems to me that choosing one of those would simplify the the problem, that is, pick one of the axis on the board, line that axis with the vertical/plumb line, gather data, and then only pay attention to that data column, every thing else is expected to be zero.This would be the equivalent of this simple device, up/down only:https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.seis-insight.eu%2Fen%2Fpublic-2%2Fplanetary-seismology%2Fhow-a-seismometer-works&psig=AOvVaw0hbdVLeTY0Ac1BO6C6ho-a&ust=1638195878340000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPDLgK2hu_QCFQAAAAAdAAAAABAUThe next step could be to consider all, x, y, and z, and map those out separately, or perhaps calculate the magnitude of the vector for with those components, from each data sample. Collecting all 3, combined with the knowledge of how the board is positioned and which axis correspond to which direction on the board, will allow for calculating the movement in any direction you choose, is you so desire.—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
