### ISSUE TITLE
Using floating point number assignment.

### ISSUE THREAD

**Issue by Inzi-Jack** [ttudrej/showspikes#3]
I tried to assign the columns to float in this last iteration of the file. have a look when you can. Note lines 17 and 18.

**Comment by Inzi-Jack** [comment]
Note lines 17 and 18

**Comment by ttudrej** [comment]
```
            Date Time  Roll  Pitch  Direction Angle  Temperature
1  2021/1/29 14:53:51  0.08   0.04           132.32        23.38
2  2021/1/29 14:53:51  0.11   0.05           127.94        23.39
```

The dataframe already has them as floats. 


"suitable na_values settings to preserve and not interpret dtype"
I take this to mean that if pandas will take a stab at assigning value type to a column based on what the values look like, in case or Roll and Pitch, they look like floats. 

From:
"dtypeType name or dict of column -> type, optional
Data type for data or columns. E.g. {‘a’: np.float64, ‘b’: np.int32, ‘c’: ‘Int64’} Use str or object together with suitable na_values settings to preserve and not interpret dtype. If converters are specified, they will be applied INSTEAD of dtype conversion."
https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html


To display or check the type for columns:
https://stackoverflow.com/questions/40353079/pandas-how-to-check-dtype-for-all-columns-in-a-dataframe

**Comment by Inzi-Jack** [comment]
Ok. So if you are right, and I misread the error message I read the other day, then the next step is to write code to access the columns I want, namely Roll and Pitch right now, and in particular read down reach column, row by row, and take the absolute value of each row entry. Once I have that info I would want to do some statics like mean, max and min. Also I would like to graph each column, maybe a graph including sections of the list that have the maximum and highest absolute values, for example. Right now I don't know where to start with the code. Some kind of iteration is needed but I haven't found examples yet. I can't even use the dataframe_to_rows to make a spreadsheet in Excel for the statistics because Excel has a maximum of a little over 1million lines and i have over 13 and a half million lines of data to examine. Let me know if you find anything.

**Comment by Inzi-Jack** [comment]
I have news. Please go see the code and result I am going to post is a few minutes. I have the dtypes listed and they are listed as objects. What does this mean? I'm going to look it up.

**Comment by ttudrej** [comment]
Re:
"then the next step is to write code to access the columns I want, namely Roll and Pitch right now, and in particular read down reach column, row by row, and take the absolute value of each row entry."

This makes it clear that you have not examined or understood the changes to `jackv6A_2.py`. 

Start by running it, the way it is, examine the output, then figure out for yourself what each line of the program does.

We're not on the same page right now, and we need to be, or it makes it impossible for me to provide any useful feedback.
